// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eekitfmfhpxffggqmeeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVla2l0Zm1maHB4ZmZnZ3FtZWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzE3MjAsImV4cCI6MjA3MTM0NzcyMH0.SS2aIKyYRAPqAKzQ91U5BTfGdj9wD-DVy_ha0dMGFrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});